In [1]:
import numpy as np

In [2]:
arreglo_0_90_grados = np.array([0,30,45,60,90])
arreglo_0_90_grados

array([ 0, 30, 45, 60, 90])

In [3]:
radianes  = arreglo_0_90_grados * np.pi /180
radianes

array([0.        , 0.52359878, 0.78539816, 1.04719755, 1.57079633])

In [4]:
np.sin(radianes)

array([0.        , 0.5       , 0.70710678, 0.8660254 , 1.        ])

In [5]:
np.sin(arreglo_0_90_grados)

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666])

In [6]:
np.cos(radianes)

array([1.00000000e+00, 8.66025404e-01, 7.07106781e-01, 5.00000000e-01,
       6.12323400e-17])

In [7]:
np.tan(radianes)

array([0.00000000e+00, 5.77350269e-01, 1.00000000e+00, 1.73205081e+00,
       1.63312394e+16])

In [11]:
arreglo_random = np.random.randint(
10 # enteros positivos + hasta 
)
arreglo_random

9

In [12]:
arreglo_random = np.random.randint(
-5,
5  # enteros positivos + hasta 
)
arreglo_random

-5

In [13]:
arreglo_random = np.random.randint(
-5,
5,
3 
)
arreglo_random

array([-1, -1,  0])

In [14]:
arreglo_random.mean()

-0.6666666666666666

In [15]:
np.median(arreglo_random)

-1.0

In [16]:
np.var(arreglo_random)

0.22222222222222224

In [17]:
np.std(arreglo_random)

0.4714045207910317